apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 572629984572.dkr.ecr.eu-central-1.amazonaws.com/tr_dev:latest
          ports:
            - containerPort: 80