apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:572629984572:certificate/d93bc089-4b04-4bf8-9b73-269a7d53862c
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: https
      port: 443
      targetPort: 80
    - name: http
      port: 80 
      targetPort: 80